services:
  userservice:
    container_name: userserver
    image: tuyenhaitan/userserver:s2
    ports:
      - 8080:8080
    depends_on:
      - hustappdb
    environment:
      KEYCLOAK_CREDENTIALS_SECRET: hW2vb3vLPhNBRW3pFzU6UiA8axdJKaP7
      KEYCLOAK_REALM: master
      KEYCLOAK_AUTH_SERVER_URL:  http://gateway.docker.internal:7080
      KEYCLOAK_SSL_REQUIRED: none
      KEYCLOAK_RESOURCE: HustApp
      KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS: true
      KEYCLOAK_BEARER_ONLY: true
      KEYCLOAK_CORS: true
      KEYCLOAK_PRINCIPAL_ATTRIBUTE: admin
      KEYCLOAK_USERNAME: admin
      KEYCLOAK_PASSWORD: admin

      SPRING_DATASOURCE_URL: jdbc:mysql://hustappdb:3306/hustappuser?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      EUREKA_INSTANCE_PREFERIPADDRESS: true
      EUREKA_CLIENT_REGISTERWITHEUREKA: true
      EUREKA_CLIENT_FETCHREGISTRY: true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

    networks:
      - hustapp



  hustappdb:
    container_name: hustappdb
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: hustappuser
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - hustapp


  eurekaserver:
    container_name: eurekaserver
    image: tuyenhaitan/eurekaserver:s1
    ports:
      - 8070:8070
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    networks:
      - hustapp


  redis:
    container_name: redis-app
    image: redis
    ports:
      - 6379:6379
    networks:
      - hustapp
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - hustapp
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - hustapp
    depends_on:
      - zookeeper

networks:
  hustapp:
    driver: "bridge"
volumes:
  elasticsearch_data:
    driver: local

